---
- hosts: all
  become: true
  tasks:
    - name: delete old deployment in Minikube
      command: kubectl delete -f /home/ubuntu/Deployment.yaml

    - name: delete old service
      command: kubectl delete -f /home/ubuntu/Service.yaml

    - name: create a new deployment
      command: kubectl apply -f /home/ubuntu/Deployment.yaml

    - name: create a service
      command: kubectl apply -f service.yaml /home/ubuntu/Service.yaml